### ISSUE TITLE
 Could not resolve dependency: npm ERR! peer react@"^16.8.6 || ^17.0.0" from @dh-react-hooks/use-raf@0.9.1

### ISSUE THREAD

**Issue by smyja** [danhuang1202/DrHooks#96]
I am using a higher version of react(react 18.1), kindly update the package.json.

**Comment by kh-mubashar** [comment]
having the same issue need a update on this  :(

**Comment by ashutosh887** [comment]
Same. I'm having only this configuration but still 
`
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0"
`

**Comment by ashutosh887** [comment]
@kh-mubashar @Smyja  Any solutions if you got???

**Comment by giancarlosisasi** [comment]
is there any solution for this? 😢

**Comment by AnassAb** [comment]
For now you can only use this with react@17 or lower, I've just submitted this PR [[44c688f](https://github.com/danhuang1202/DrHooks/pull/116/commits/44c688ffffb6c4e596e95b48ca5098a4d8572b65)] that can solve this issue.

**Comment by danhuang1202** [comment]
I had add react@18 as peer dependency and published.
